### ISSUE TITLE
Empty post title breaks import script

### ISSUE THREAD

**Issue by fabienheureux** [wagtail/wagtail-wordpress-import#130]
In the xml dump I use, there are some posts with empty titles `<title></title>`.
  
In that case, the import script raises an error and stops.   
What do you think of these solutions :
- :a: generate a fallback title and import the post
- :b: do not import this post

<details>
<summary>Traceback</summary>  
  
```python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/src/wagtail-wordpress-import/wagtail_wordpress_import/management/commands/import_xml.py", line 70, in handle
    importer.run(
  File "/usr/local/src/wagtail-wordpress-import/wagtail_wordpress_import/importers/wordpress.py", line 113, in run
    wp_post_id=wordpress_item.cleaned_data.get("wp_post_id")
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/usr/local/src/wagtail-wordpress-import/wagtail_wordpress_import/importers/wordpress.py", line 509, in cleaned_data
    "title": self.cleaned_title(),
  File "/usr/local/src/wagtail-wordpress-import/wagtail_wordpress_import/importers/wordpress.py", line 368, in cleaned_title
    return self.node["title"].strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```
</details>

**Comment by nickmoreton** [comment]
I like the idea of a fallback title. What would you call it?

In fact I too have seen this issue with https://codex.wordpress.org/Theme_Unit_Test when I tested it.

**Comment by fabienheureux** [comment]
Thanks for the fix @nickmoreton !
